---
driver:
  name: "terraform"
  root_module_directory: "examples/asg_lc_test_fixture"

provisioner:
  name: "terraform"

platforms:
  - name: "aws"

verifier:
  name: "awspec"

suites:
  - name: "default"
    verifier:
      name: "awspec"
      patterns:
      - "test/integration/default/asg_lc_tests.rb"
